name: Skitourenwoche
favicon: null
layout_spectrum: 0.16528
typography_spectrum: 0.69616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-58154788-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6182bb'
    - '#060918'
    - '#83bffa'
    - '#c3eafe'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
