name: Skitourenwoche
favicon: null
layout_spectrum: 0.20086380140855908
typography_spectrum: 0.5047047515399754
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7909743445925415
  lightness: 0.32522582169622183
  saturation: 0.764219032600522
  rhythmicContrast: 0.7224305486306548
purpose: []
