typography_spectrum: 0.69616
color:
  brandColors:
    - '#92a0b9'
    - '#fffeff'
    - '#37629d'
    - '#cfd5e5'
    - '#17315b'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4329
analytics:
  google: UA-58154788-2
  facebook: null
  twitter: null
name: Skitourenwoche
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Skitourenwoche
purpose: []
