name: Skitourenwoche
favicon: null
layout_spectrum: 0
typography_spectrum: 0.81803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6182bb'
    - '#060918'
    - '#83bffa'
    - '#c3eafe'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
